### ISSUE TITLE
Seleção da skill Designer

### ISSUE THREAD

**Issue by rafaewo** [rafaewo/Hackatinder#11]
Por algum motivo, a skill _designer_ não é adicionada no momento do cadastro. (CadastrarUsuario.js)

**Comment by EclesioMeloJunior** [comment]
Vou analisar agora esse bug

**Comment by EclesioMeloJunior** [comment]
### Motivo do problema
- O formulário é controlado pelo state do component
- O state do component tem uma **prop** chamda **skill** que armazena o valor da skill selecionada
- Essa prop estava sendo inicializada da seguinte forma: `skill: ''`
- O select tinha as seguintes opções:
```html
<select value={state.skill} onchange={...}>
    <option value={'Designer'}>Designer</option>
    <option value={'Frontend'}>Frontend</option>
    <option value={'Backend'}>Backend</option>
    <option value={'Gerente'}>Gerente</option>
</select>
```
- Por padrão no select o primeiro option é exibido, então o **Designer** era exibido porém o valor real da prop **skill** ainda estava vazio
